#! /usr/bin/php

<?php

require('system/lib/cli.functions.php');

$plugin = $argv[1];
$script = $argv[2];

require('plugins/'.$plugin.'/cli/'.$script.'.php');

if($success)
{
  success($success);
}

if($error)
{
  error($error);
}

echo "\n";
